# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Excursão',
                'verbose_name_plural': 'Excursões',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('texto', models.CharField(max_length=200, verbose_name='Texto')),
                ('excursao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabalho.Excursao')),
            ],
        ),
    ]
