# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalho', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='excursao',
        ),
        migrations.AddField(
            model_name='excursao',
            name='endereco',
            field=models.CharField(default='0', max_length=100, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excursao',
            name='texto',
            field=models.CharField(default='0', max_length=200, verbose_name='Texto'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
