# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalho', '0004_auto_20170716_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='data',
            field=models.DateField(),
        ),
    ]
