# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalho', '0005_auto_20170716_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='data',
            field=models.CharField(max_length=10, verbose_name='Data'),
        ),
    ]
