# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabalho', '0006_auto_20170716_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shows',
            old_name='nome',
            new_name='local',
        ),
    ]
