# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalho', '0008_auto_20170716_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='data',
            field=models.DateField(),
        ),
    ]
